module.exports = {
    start: [
        {
            type: 'autogenerated',
            dirName: 'start'
        }
    ],
    api: [
        {
            type: 'autogenerated',
            dirName: 'api'
        }
    ],
    topics:[
        {
            type: 'autogenerated',
            dirName: 'topics'
        }
    ],
    status: [
        {
            type: 'autogenerated',
            dirName: 'status'
        }
    ],
    support: [
        {
            type: 'autogenerated',
            dirName: 'support'
        }
    ],
    achievementRewards: [
        {
            type: 'autogenerated',
            dirName: 'internal/achievement-rewards'
        }
    ],
    gepWebsockets: [
        {
            type: 'autogenerated',
            dirName: 'internal/websocket-gep'
        }
    ]
}