module.exports = {
  start: [
    {
      type: 'autogenerated',
      dirName: 'start',
    },
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  topics: [
    {
      type: 'autogenerated',
      dirName: 'topics',
    },
  ],
  tools: [
    {
      type: 'autogenerated',
      dirName: 'tools',
    },
  ],
  status: [
    {
      type: 'autogenerated',
      dirName: 'status',
    },
  ],
  legal: [
    {
      type: 'autogenerated',
      dirName: 'legal',
    },
  ],
  support: [
    {
      type: 'autogenerated',
      dirName: 'support',
    },
  ],
  achievementRewards: [
    {
      type: 'autogenerated',
      dirName: 'internal/achievement-rewards',
    },
  ],
  gepWebsockets: [
    {
      type: 'autogenerated',
      dirName: 'internal/websocket-gep',
    },
  ],
};
